
# @cluster = https://kafkaconnect-jdbc.elisabeth.mytaxi.com
# @cluster = https://kafkaconnect-surge-price.elisabeth.mytaxi.com
@cluster = http://localhost:8083
@connector_name=mssql-debezium-source


###### List the connectors ##########

curl {{cluster}}/connectors

####### Describe Connector ######

curl {{cluster}}/connectors/{{connector_name}}

####### Describe Connector config ######

curl {{cluster}}/connectors/{{connector_name}}/config

####### check the status of a Connector ######

curl {{cluster}}/connectors/{{connector_name}}/status


#### Restart connector #########

POST {{cluster}}/connectors/{{connector_name}}/restart
# curl -X POST -H {{cluster}}/connectors/{{connector_name}}/restart

#### Pause connector #########

PUT {{cluster}}/connectors/{{connector_name}}/pause

#curl -X PUT -H {{cluster}}/connectors/{{connector_name}}/pause

#### Resume connector #########
PUT {{cluster}}/connectors/{{connector_name}}/resume
#curl -X PUT -H {{cluster}}/connectors/{{connector_name}}/resume

######### Get tasks of a connector ######

curl {{cluster}}/connectors/{{connector_name}}/tasks

######### Restart a task of a connector ##########

POST {{cluster}}/connectors/{{connector_name}}/tasks/0/restart

      "transforms.extractkey.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
      "transforms.extractkey.field": "Id",
      "key.converter": "org.apache.kafka.connect.converters.IntegerConverter",


###### Delete a Connector ###########
curl -X DELETE {{cluster}}/connectors/mssql-debezium-source6

##############

POST {{cluster}}/connectors
Content-Type: application/json
Accept: application/json
  
{
    "name": "mssql-debezium-source6",
    "config": {
      "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector", 
      "database.hostname": "mssql", 
      "database.port": "1433", 
      "database.user": "sa", 
      "database.password": "Test@123456789", 
      "database.dbname": "test", 
      "database.server.name": "mssql_1", 
      "table.include.list": "dbo.Employees", 
      "database.history.kafka.bootstrap.servers": "broker:29092", 
      "database.history.kafka.topic": "dbhistory.mssql_1",
      "transforms": "unwrap",
      "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
      "transforms.extractkey.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
      "transforms.extractkey.field": "Id",
      "key.converter": "io.confluent.connect.avro.AvroConverter",
      "key.converter.schema.registry.url": "http://schema-registry:8081",
      "value.converter": "io.confluent.connect.avro.AvroConverter",
      "value.converter.schema.registry.url": "http://schema-registry:8081"
    }
}


