
# @cluster = https://kafkaconnect-jdbc.elisabeth.mytaxi.com
# @cluster = https://kafkaconnect-surge-price.elisabeth.mytaxi.com
@cluster = http://localhost:8083
@connector_name=CsvSpoolDir


###### List the connectors ##########

curl {{cluster}}/connectors

####### Describe Connector ######

curl {{cluster}}/connectors/{{connector_name}}

####### Describe Connector config ######

curl {{cluster}}/connectors/{{connector_name}}/config

####### check the status of a Connector ######

curl {{cluster}}/connectors/{{connector_name}}/status


#### Restart connector #########

POST {{cluster}}/connectors/{{connector_name}}/restart
# curl -X POST -H {{cluster}}/connectors/{{connector_name}}/restart

#### Pause connector #########

PUT {{cluster}}/connectors/{{connector_name}}/pause

#curl -X PUT -H {{cluster}}/connectors/{{connector_name}}/pause

#### Resume connector #########
PUT {{cluster}}/connectors/{{connector_name}}/resume
#curl -X PUT -H {{cluster}}/connectors/{{connector_name}}/resume

######### Get tasks of a connector ######

curl {{cluster}}/connectors/{{connector_name}}/tasks

######### Restart a task of a connector ##########

POST {{cluster}}/connectors/{{connector_name}}/tasks/0/restart

###### Delete a Connector ###########
curl -X DELETE {{cluster}}/connectors/CsvSpoolDir

##############

POST {{cluster}}/connectors
Content-Type: application/json
Accept: application/json
  
{
  "name" : "cassandraSinkConnector1",
  "config" : {
    "connector.class" : "io.confluent.connect.cassandra.CassandraSinkConnector",
    "tasks.max" : "1",
    "topics" : "cities",
    "cassandra.contact.points" : "cassandra",
    "cassandra.keyspace" : "test",
    "cassandra.local.datacenter": "datacenter1",
    "confluent.topic.bootstrap.servers": "broker:29092",
    "transforms":"copyFieldToKey",
    "transforms.copyFieldToKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
    "transforms.copyFieldToKey.fields":"City"
  }
}

##############

POST {{cluster}}/connectors
Content-Type: application/json
Accept: application/json

{
    "name": "CsvSpoolDir",
    "config": {
      "tasks.max": "1",
      "connector.class": "com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector",
      "input.path": "/data/filestream",
      "input.file.pattern": "cities.csv",
      "error.path": "/tmp",
      "finished.path": "/tmp",
      "halt.on.error": "false",
      "topic": "cities",
      "csv.first.row.as.header": "true",
      "schema.generation.enabled": "true"
    }
}

#### Update connector
PUT https://kafkaconnect.dev-platform.mep.eu-central-1.aws.int.kn/connectors/kn.client6sa.testconnector/config HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Basic mep-super-user:3CgV&fB$9ajEy+:R

